Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.default.urls')),
    path('', include('myapp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

myapp/urls.py
from django.urls import path
from myapp.views import send_email,order,products,detail,cart_view,return_view,cancel_view,review,category,address_view
app_name='myapp'

urlpatterns = [
 path('',category,name='category'),
 path('products/<int:product_id>/<slug:slug>',products,name='products'),
 path('<int:product_id>/<slug:slug>',detail,name='detail'),
 path('cart/',cart_view,name='cart_view'),
 path('order/',order,name='order'),
 path('success/',return_view,name='return_view'),
 path('cancel/',cancel_view,name='cancel_view'),
 path('sendemail/',send_email,name="send_email"),
 path('<int:product_id>/<slug:slug>/review/',review,name='review'), 
 path('address/',address_view, name='address_view'),
 ]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Category(models.Model):
    title=models.CharField(max_length=50)
    img=models.ImageField(upload_to='')
    slug=models.SlugField()
    def __str__(self):
        return self.title

class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    
    book_available=models.BooleanField(default=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    def __str__(self):
        return self.title
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.product.title+'_'+str(self.id)
class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    # Add other book details like ISBN, genre, etc.

    def __str__(self):
        return self.title
class Address(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField(blank=True, null=True)

    def _str_(self):
        return self.user.username

class Rent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Product, on_delete=models.CASCADE)
    rent_date = models.DateTimeField(default=timezone.now)
    return_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} rented {self.book.title}"

class Fine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rent = models.OneToOneField(Rent, on_delete=models.CASCADE)
    fine_amount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"Fine for {self.rent.user}'s rent on {self.rent.book.title}"
        
class Order(models.Model):
    name = models.CharField(max_length=100)

    city = models.CharField(max_length=100)
    pincode = models.CharField(max_length=10)
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField(max_length=100)
    address = models.TextField()

    def __str__(self):
        return self.name
class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True
class Review(TimeStamp):
	post = models.ForeignKey(Product,on_delete = models.CASCADE)
	review = models.TextField()

	def __str__(self):
		return self.review         

myapp/forms.py
from django import forms
from myapp.models import Review
from myapp.models import Order
class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)
class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ['review']

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

myapp/views.py
from django.shortcuts import get_object_or_404,render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from myapp.models import Product,Cart,Buy,Review,Category,Address
from myapp.forms import CartForm,ReviewForm,OrderForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def category(request):
    if 'q' in request.GET:
        q=request.GET['q']
        c=Category.objects.filter(title__icontains=q)
    else:
         c= Category.objects.all()
    context={'c':c}
    return render(request,'categories.html',context) 
def products(request,product_id,slug):
    p=Product.objects.filter(category=product_id)
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    reviews = Review.objects.filter(post_id = product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')

    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f,'reviews':reviews}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id') 
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
def address_view(request):
    if request.method=='POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp:order') 
        else:
            form = OrderForm()
    return render(request,"address.html")
@login_required
def order(request):
    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price\
              =i.price)
        b.save()
    paypal_dict = {
        "business": "sb-l7r2e28145955@business.example.com",
        "amount": total_(request),
        "item_name": cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return render(request,'transaction.html')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')
def create_rewiew(request):
    if request.method=='POST':
        form=ReviewForm(request.POST)
        if form.is_valid():
            rewiew=form.save(commit=False)
            rewiew.user=request.user
            rewiew.save()
            return redirect('product_detail',pk=review.product.pk)
        else:
            form=ReviewForm()
            return render(request,'create_review.html',{'form':form})
@login_required
def review(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    reviews = Review.objects.filter(post_id = product_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.cleaned_data['review']
            c = Review(post_id = product_id,review = review,user = request.user)
            c.save()
            
    else:
        form = ReviewForm()

    return render(request, 'review.html', {'d':d,'form': form,'reviews':reviews})
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect        

def send_email(request):
    subject = request.POST.get("subject", "Welcome to my bookstore")
    message = request.POST.get("message", "otp is 222111")
    from_email = request.POST.get("from_email", "maadunandini2003@gmail.com")
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ["snandini1109@gmail.com"])
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return HttpResponseRedirect("Mail sent to me")
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse("Make sure all fields are entered and valid.")


        

myapp/templates/address.html
{% extends 'base.html' %}
{% block content %}
<style>
    .gradient-custom {
background: -webkit-linear-gradient(left, #d3d2db, #0aea49);
}

.card-custom {
border-bottom-left-radius: 10% 50%;
border-top-left-radius: 10% 50%;
background-color: #1478dd ;
}


.input-custom {
background-color: rgb(234, 240, 236) ;
}

.white-text {
color: hsl(0, 17%, 91%);
font-weight: 100 ;
font-size: 14px;
}

.back-button {
background-color: hsl(251, 94%, 49%);
font-weight: 700;
color: rgb(17, 214, 43) ;
margin-top: 50px ;
}
</style>
<div class="row mt-3 mx-3" style="margin-top:25px ;">
    <div class="col-md-3">
      <div style="margin-top: 50px; margin-left: 10px;" class="text-center">
        <i id="animationDemo"  data-mdb-animation="slide-right" data-mdb-toggle="animation"
          data-mdb-animation-reset="true" data-mdb-animation-start="onScroll"
          data-mdb-animation-on-scroll="repeat" style="color: #200bdc ;" class="fas fa-3x fa-shipping-fast text-primary"></i>
        <h3 class="mt-3 text-dark">Welcome</h3>
      </div>
      <div class="text-center">
        &nbsp;&nbsp;&nbsp;<a href="{% url 'myapp:category' %}" type="submit" class="btn btn-white btn-rounded back-button">Back to Home</a>
      </div>
  
  
    </div>
    <div class="col-md-9 justify-content-center">
      <div class="card card-custom pb-4">
        <div class="card-body mt-0 mx-5">
          <div class="text-center mb-3 pb-2 mt-3">
            <h4 style="color: #495057 ;">Delivery Details</h4>
          </div>
  
          <form class="mb-0"  method="POST">
            {% csrf_token %}
            <div class="row mb-4">
              <div class="col">
                <div class="form-outline">
                  <label class="form-label" for="form9Example1">Name</label>
                  <input type="text" required id="form9Example1" class="form-control input-custom" name="name">
                </div>
              </div>
              </div>
            <div class="row mb-4">
              <div class="col">
                <div class="form-outline">
                  <label class="form-label" for="form9Example3">City</label>
                  <input type="text" required id="form9Example1" class="form-control input-custom" name="city">
                </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <label class="form-label" for="form9Example4">pincode</label>
                  <input type="number" required id="form9Example1" class="form-control input-custom" name="pincode">
                </div>
              </div>
            </div>
                <div class="row mb-4">
                    <div class="col">
                      <div class="form-outline">
                        <label class="form-label" for="form9Example6">Mobile number</label>
                        <input type="number" required id="form9Example1" class="form-control input-custom" name="mobile_number">
                      </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <label class="form-label" for="typeEmail">Email</label>
                  <input type="email"  required id="typeEmail" class="form-control input-custom" name="email"/>
                </div>
              </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                  <div class="form-outline">
                    <label class="form-label" for="form9Example6">Address</label>
                    <input type="text" required id="form9Example6" class="form-control input-custom" name="address"/>
                  </div>
  <br>

            <div class="float-end">
              <button type="submit"  class="btn btn-primary btn-rounded" style="background-color: #0df02b;"">submit </button>
              <!-- Submit button -->
            </div>
  
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, 
    initial-scale=1.0">
    <title>BOOK STORE</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<style>
  html {
  scroll-behavior: smooth;
}
  * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

/* Styling the header and navigation */
header {
  background-color: #333;
  color: #fff;
  padding: 10px 20px;
}

nav ul {
  list-style: none;
}

nav ul li {
  display: inline;
  margin-right: 20px;
}

nav ul li a {
  color: #fff;
  text-decoration: none;
}

/* Styling sections */
section {
  height: 75vh; /* Adjust to fit your design */
  display: flex;
  justify-content: center;
  align-items: center;
  scroll-margin-top: 50px; /* Adjust to offset fixed header height */
}

section:nth-child(odd) {
  background-color: #f0f0f0;
}

section:nth-child(even) {
  background-color: #fafaf6;
}

/* Smooth scrolling behavior */
html {
  scroll-behavior: smooth;
}
  *{
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    box-sizing: border-box;
  }
    body{
      background-image: url(https://img.freepik.com/premium-photo/abstract-white-background-with-squares_476363-1053.jpg?w=1380);
      background-size: cover;
    }
      body{
    height: 100vh;
    align-items: center;
    justify-content: center;
}
    

       a 
       { 
        color: bisque;
       }
</style>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      <a href="{% url 'myapp:category' %}"><img src="https://img.pikbest.com/origin/09/34/43/09IpIkbEsTUZA.png!sw800" width="150" height="130" class="d-inline-block align-top" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myapp:category' %}"><h1><b>Home</b></h1> <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <h3>
          <form class="form-inline my-2 my-lg-0">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<form class="example" action="/action_page.php" style="margin:auto;max-width:300px">
              <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="Search.." name="search2"><button class="form-control mr-sm-2" type="submit"><i class="fa fa-search"></i></button>
            </form><br>
           
          </form>
          {{user}}&nbsp;&nbsp;&nbsp;
          {% if not user.is_authenticated %}
          <a class="btn btn-outline-primary my-2 my-sm-0" href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-log-in">&nbsp;Login</a></span>&nbsp;&nbsp;
          <a class="btn btn-outline-primary my-2 my-sm-0" href="{% url 'registration_register' %}"><i class="fa fa-user-circle-o">&nbsp;Register</a></i> &nbsp;&nbsp;
      {% else %}
      &nbsp;&nbsp;<a href="{% url 'myapp:cart_view' %}"> 🛒</a> &nbsp;&nbsp;

          <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'auth_logout' %}"><span class="glyphicon glyphicon-log-out">&nbsp;Logout</span></a>&nbsp;&nbsp;
      {% endif %}
      <a  class="btn btn-outline-secondary my-2 my-sm-0"  href="/admin/">Staff</a>
        </div></h3>
            </nav>
{% block content %}

{% endblock %}
    </body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
</style>
<center><h1>SHOPPING CART</h1>
<div class="container">
<div class="row">
  <div class="col-lg-12">
<div class="box-element">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">S.No</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Cost</th>
      </tr>
    </thead>
    <tbody>
        {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
    </td>
      </tr>
      
      {% endfor %}
    </tbody>
  </table><br>
  &nbsp;&nbsp;Total: ₹{{t}}<br>
  <br>
&nbsp;&nbsp;<a class="btn btn-secondary" href="{% url 'myapp:address_view' %}">Order</a>
&nbsp;&nbsp;&nbsp;
<a class="btn btn-secondary" href="{% url 'myapp:category' %}">Back</a>
</div></div></div></div></center>
  {% endblock %}

myapp/templates/categories.html
{% extends 'base.html' %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="https://images.ctfassets.net/9htf9uzhsn4z/stfKpvw1vQdXDm5tCQ7vf/a78ea71bf834bfa55e501519d93c8569/lulu-create-magazines-main-banner-1x.jpg?w=2000&h=720&fm=webp" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.ctfassets.net/9htf9uzhsn4z/2ddNTGCnhVsjRduLXWvDtC/8e6cdb049cf11ced4b719b58a4bec87f/lulu-home-0223-main-banner.jpg?w=2000&h=720&fm=webp" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.ctfassets.net/9htf9uzhsn4z/6djHFg9w78eMrWzHMGQ7AX/d56259c6bac421dd61e9e7f4e717d69f/lulu-print-books-main-banner-2x.jpg?fm=webp" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div></div>
  <br>
  <div class="container">
<div class="row">
    {% for i in c %}
     <div class="col-md-4">
        <div class="card border-primary mb-2">
       <center><b><a>{{i.title}}</a></b>
        <br><img src="{{i.img.url}}" width="200" height="150" alt="">
       <br> <a class="btn btn-outline-danger my-2 my-sm-3" style="width: 3cm;" href="{% url 'myapp:products' i.id i.slug %}">View</a></center>
    <br></div></div>
    {% endfor %}
</div>
</div>
<br><br>
<div class="card primary card-expand-lg bg-secondary">
    <br> <center><h1>CONTACT US</h1></center>
    <h5><i class="material-icons">place:-</i><a href="https://www.google.com/maps/place/Parvathaneni+Brahmayya+Siddhartha+college+of+Arts+%26+Science/@16.5055349,80.6469164,17z/data=!4m15!1m8!3m7!1s0x3a35fab6cd09a89b:0xd33167f96ffe60b7!2sGJ4X%2B6Q9+PB+Siddhartha+College+Gym,+Mogalrajapuram,+Siddhartha+Nagar,+Benz+Circle,+Vijayawada,+Andhra+Pradesh+520010!3b1!8m2!3d16.5055298!4d80.6494913!16s%2Fg%2F1hhj1fh8g!3m5!1s0x3a35fab12587c72b:0x20aec0bac504143c!8m2!3d16.5050802!4d80.648373!16s%2Fg%2F1tzvtzmq?entry=ttu" class="text-dark">PARVATHANENI BRHAMAYYA SIDDHARTHA COLLEGE OF ARTS AND SCINCE</a></h5>
    <h5><i class="material-icons">local_phone:-</i>0866-2475966</h5>
    <h5><i class="material-icons">mail:-</i>pbs_college@hotmail.com</h5>
    <CENTER><h2>FOLLOW US</h2></CENTER>
    <h4> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://twitter.com/i/flow/login?redirect_after_login=%2FPBSiddharthaco2" class="text-dark"  style='font-size:24px'><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;<a href="https://www.facebook.com/pbsiddharthaclg/" class="text-dark" style='font-size:24px'><i class="material-icons" class="text-dark">facebook</i></a>&nbsp;&nbsp;<a href="https://www.instagram.com/pbsiddharthacollege/" class="text-dark" style='font-size:24px'><i class="fa fa-instagram"></i></a>&nbsp;&nbsp;<a href="https://www.linkedin.com/school/parvathaneni-brahmayya-siddhartha-college-of-arts-&-science/?originalSubdomain=in" class="text-dark" style='font-size:24px'><i class="fa fa-linkedin-square"></i></a></h4>
  <br>
    <br>
   </div></div>
{% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="card border-success">
<div class="row">
    &nbsp;<div class="col-md-6">
  &nbsp; <b>{{d.title}}</b><br>
    &nbsp; {{d.description}}<br>
     <br><h2>₹{{d.price}}</h2><br>
      </div>
    <div class="col-md-4">
       <br> <img src="{{d.img.url}}" width=400 height="500">
    </div>

</div>
{% if user.is_authenticated %}
  <form action="{% url 'myapp:detail' d.id d.slug %}" method="post">
    {% csrf_token %}
    {{ f }}
   <input type="submit" class="btn btn-outline-success" value="Add to Cart">
</form>
{% else %}
<p>To order the book please <a href="{% url 'auth_login' %}">login</a></p>
{% endif %}

<center><form action="{% url 'myapp:review' d.id d.slug %}" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-outline-dark" value="Add to Reviews">
</form></center><br>
<div class="container">
	<h6>Reviews:</h6>
    
    {% for i in reviews %}

    {{forloop.counter}} - {{i.review}} <br>
    at {{i.created_at}} by {{user}} <br>

    {% endfor %}

</div>
</div>
</div>
{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row"><br>
    {% for i in p %}
    <div class="w3-container">
    <br>
    <div class="col-md-6">
      <div class="card border-primary mb-1" style="width: 25rex; height: 25rem;">
      <b>{{i.title}}</b></a>
      <center><img src="{{i.img.url}}" width=190 height=180 alt=""><br></center><br>
      <b>&nbsp;&nbsp;₹{{i.price}}</b>
      {% if i.book_available is True %}
      <center><b><li class="text-success">IN STOCK</li></b></center>
      <center><a class="btn btn-outline-primary my-2 my-sm-3" style="width: 3cm;" href="{% url 'myapp:detail' i.id i.slug %}">View</a></center>
      <br>
      {% else %}
      <br><center><b><li class="text-danger">Out of stock</li></b></center>
      {% endif %}
    </div>
  </div>
</div>
    {% endfor %}
</div>

{% endblock %}

myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<style>
    body
    {
        font-size: large;
    }
</style>
<center>
    <div class="card border-primary"> 
<h1><b>Cart:</b></h1><br>
<b>{% for i in items %}
{{i.product}}<br>
{% endfor %}
Pay:₹{{total}}</b>
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
</div>
</center>
{% endblock %}